

# [build] : Cette section définit la configuration de construction pour votre projet.
[build]
  # command : La commande qui sera exécutée pour construire votre application.
  command = "react-scripts build"
  
  # functions : Le répertoire où se trouvent vos fonctions serverless (s'il y en a).
  functions = "netlify/functions"
  
  # publish : Le répertoire à partir duquel les fichiers finaux de l'application seront servis.
  publish = "build"

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev] : Cette section est optionnelle et est utilisée pour configurer Netlify Dev, un outil pour le développement local.
  [dev]
    # command : La commande pour démarrer votre serveur de développement local.
    command = "yarn start"
    
    # port : Le port sur lequel le serveur de développement local doit écouter.
    port = 3000
    
    # publish : Le répertoire contenant le contenu statique pour le fichier "_redirect" utilisé par Netlify Dev.
    publish = "dist"

  ## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/

# [[redirects]] : Cette section est commentée par défaut, mais vous pouvez la décommenter si vous développez une SPA.
# Elle permet de définir des redirections pour gérer les routes SPA en renvoyant toutes les URL vers "index.html" avec un statut HTTP 200.
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200
